server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_notice?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis:
  mapperLocations: classpath:/mapper/*.xml
