server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_notice?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #配置JDK代理
 # aop:
  #  proxy-target-class: false

#数据库
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  configuration:
    #配置sql超时
    default-statement-timeout: 30
    #驼峰命名规则
    map-underscore-to-camel-case: true

#日志
logging:
  level:
    com:
      cy: debug
  file:
    path: D:\CGDIII\log
