server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbpms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapperLocations: classpath:/mapper/*/*.xml

logging:
  level:
    com.cy: debug
shiro:
  loginUrl: /login.html
  rememberMeManager:
    cookie:
      maxAge: 3600